export const adminHTML = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>SGIA · 관리자</title><style>*{box-sizing:border-box}body{margin:0;background:#111b29;color:#dce5ef;font:14px/1.7 system-ui,sans-serif}main{max-width:1050px;margin:50px auto;padding:25px}h1{font-size:26px}button,input,select{font:inherit;border:1px solid #7996b344;border-radius:10px;background:#223147;color:inherit;padding:10px 14px}button{cursor:pointer}button:hover{background:#354a64}input{width:100%}button:disabled{opacity:.5}a{color:#9ddae0}form{display:grid;gap:15px;max-width:450px;padding:25px;border:1px solid #7996b333;border-radius:18px}small,.muted{color:#99abc1;font-size:11px}.bar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:25px 0}.bar h2{flex:1}article{border:1px solid #7996b333;border-radius:15px;padding:22px;margin:15px 0;background:#182638}article.hidden{opacity:.65}article p{white-space:pre-wrap;overflow-wrap:anywhere}.tools{display:flex;gap:8px;flex-wrap:wrap}.tools button{font-size:11px;padding:7px 10px}.ip{font-family:monospace;color:#dfaea9}#status{min-height:28px;color:#d9b88b}.comment{border-top:1px solid #7996b333;padding-top:15px;margin-top:15px}.comment p{font-size:12px}#audit{white-space:pre-wrap;font:11px/1.9 monospace;overflow-wrap:anywhere}[hidden]{display:none!important}</style><script src="/admin/app.js" defer></script></head><body><main><small>SGIA / OWNER CONSOLE</small><h1>커뮤니티 관리자</h1><p class="muted">체험 직원 모드와 별개의 본인 전용 관리 채널 · 8시간 세션</p><p id="status" role="status"></p><form id="login"><label for="key">관리자 비밀 키</label><input id="key" type="password" autocomplete="current-password" required maxlength="200"><button>관리자 인증</button><small>최초 발급한 로컬 비공개 안내 파일의 키를 사용합니다. 공개 게시판에 입력하지 마세요.</small></form><section id="workspace" hidden><div class="bar"><h2>게시물 관리</h2><button id="refresh">새로고침</button><button id="audit-button">관리 로그</button><button id="blocks-button">차단 목록</button><button id="logout">로그아웃</button></div><p class="muted">숨김은 되돌릴 수 있습니다. 삭제는 본문을 제거합니다. IP는 작성일로부터 30일 동안만 확인할 수 있으며 열람 사실이 기록됩니다.</p><div id="posts"></div><div class="bar"><button id="prev">이전</button><span id="page"></span><button id="next">다음</button></div><pre id="audit"></pre><div id="blocks"></div></section></main></body></html>`;
export const adminJS = String.raw`
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let offset=0;
async function api(path,method='GET',data){const r=await fetch('/admin/'+path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,credentials:'same-origin'});const result=await r.json();if(!r.ok){if(r.status===401){$('#login').hidden=false;$('#workspace').hidden=true;}throw Error(result.error||'관리 요청 실패');}return result;}
function message(e){$('#status').textContent=e.message||e;}
function actions(kind,id,hidden,deleted){return '<div class="tools" data-kind="'+kind+'" data-id="'+id+'">'+(deleted?'': '<button data-action="'+(hidden?'restore':'hide')+'">'+(hidden?'복원':'숨김')+'</button><button data-action="delete">삭제</button>')+'<button data-action="ip">작성 IP 열람</button><button data-action="block">해당 IP 30일 차단</button></div><p class="ip" id="ip-'+id+'"></p>';}
async function load(){const result=await api('posts?offset='+offset);$('#login').hidden=true;$('#workspace').hidden=false;$('#posts').innerHTML=result.posts.map(p=>'<article class="'+(p.hidden?'hidden':'')+'"><small>'+esc(p.board)+' / '+esc(p.id)+' / '+new Date(p.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+'</small><h3>'+esc(p.title)+'</h3><small>'+esc(p.author)+' · '+esc(p.department)+(p.deleted_at?' · 삭제됨':p.hidden?' · 숨김':'')+'</small><p>'+esc(p.body)+'</p>'+actions('post',p.id,p.hidden,p.deleted_at)+'<button data-comments="'+p.id+'">댓글 관리</button><div id="comments-'+p.id+'"></div></article>').join('')||'<p>게시물이 없습니다.</p>';$('#page').textContent=offset/30+1;$('#prev').disabled=offset===0;$('#next').disabled=result.posts.length<30;}
$('#login').onsubmit=async e=>{e.preventDefault();const key=$('#key').value;$('#key').value='';try{await api('login','POST',{key});message('인증 완료');await load();}catch(err){message(err);}};
$('#refresh').onclick=()=>load().catch(message);$('#logout').onclick=async()=>{try{await api('logout','POST',{});$('#workspace').hidden=true;$('#login').hidden=false;$('#posts').replaceChildren();message('로그아웃했습니다.');}catch(e){message(e);}};
$('#prev').onclick=()=>{offset=Math.max(0,offset-30);load().catch(message);};$('#next').onclick=()=>{offset+=30;load().catch(message);};
$('#posts').onclick=async e=>{try{const comment=e.target.closest('[data-comments]');if(comment){const data=await api('comments?post='+comment.dataset.comments);$('#comments-'+comment.dataset.comments).innerHTML=data.comments.map(c=>'<div class="comment"><small>'+esc(c.author)+' · '+new Date(c.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+(c.hidden?' · 숨김':'')+(c.deleted_at?' · 삭제됨':'')+'</small><p>'+esc(c.body)+'</p>'+actions('comment',c.id,c.hidden,c.deleted_at)+'</div>').join('')||'<p>댓글 없음</p>';return;}const button=e.target.closest('[data-action]');if(!button)return;const box=button.closest('[data-kind]'),id=box.dataset.id,kind=box.dataset.kind,action=button.dataset.action;button.disabled=true;try{if(action==='ip'){const r=await api('ip','POST',{id});$('#ip-'+id).textContent=r.ip||'보관 기간 만료 또는 IP 없음';}else{if((action==='delete'||action==='block')&&!confirm(action==='delete'?'본문이 삭제되며 복구할 수 없습니다. 삭제할까요?':'이 IP의 작성을 30일 차단할까요?'))return;await api('moderate','POST',{kind,id,action});message('관리 작업 완료');await load();}}finally{button.disabled=false;}}catch(err){message(err);}};
$('#audit-button').onclick=async()=>{try{const r=await api('audit');$('#audit').textContent=r.results.map(x=>new Date(x.created_at).toISOString()+' '+x.action+' '+x.target).join('\n')||'관리 로그 없음';}catch(e){message(e);}};
$('#blocks-button').onclick=async()=>{try{const r=await api('blocks');$('#blocks').innerHTML=r.results.map(x=>'<p>'+esc(x.ip_hash.slice(0,12))+'… / '+new Date(x.expires).toLocaleDateString()+' <button data-unblock="'+esc(x.ip_hash)+'">차단 해제</button></p>').join('')||'<p>차단 없음</p>';}catch(e){message(e);}};
$('#blocks').onclick=async e=>{const b=e.target.closest('[data-unblock]');if(!b)return;try{await api('unblock','POST',{hash:b.dataset.unblock});b.parentElement.remove();message('차단 해제 완료');}catch(err){message(err);}};
load().catch(e=>{if(!e.message.includes('인증'))message(e);});
`;
